* Reset boot variant after installation or rollout (Bug #28327)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucc@37870 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/univention-ucc-initramfs/initramfs-tools/scripts/ucc b/univention-ucc-initramfs/initramfs-tools/scripts/ucc
--- a/univention-ucc-initramfs/initramfs-tools/scripts/ucc
+++ b/univention-ucc-initramfs/initramfs-tools/scripts/ucc
@@ -837,6 +837,14 @@ ucc_rollout ()
 	fi
 }
 
+set_boot_variant ()
+{
+	# Reset the boot flag for this client
+	if ! chroot /root /usr/share/univention-ucc-initramfs/scripts/set_boot_variant.sh none; then
+		echo "Failed to reset the boot flag."
+	fi
+}
+
 mountroot()
 {
 	[ "$quiet" != "y" ] && log_begin_msg "Running /scripts/local-top"
@@ -895,6 +903,7 @@ mountroot()
 		echo "Starting UCC installation mode"
 		sleep 1 # Give udevadm one more second
 		ucc_installation
+		set_boot_variant
 	elif [ "$UCC" = "update" ]; then
 		echo "Starting UCC update mode"
 		_start_dhcpclient "$net_dev"
@@ -904,6 +913,7 @@ mountroot()
 		_start_dhcpclient "$net_dev"
 		ucc_update
 		ucc_rollout
+		set_boot_variant
 	elif [ "$UCC" = "local" -o "$UCC" = "none" ]; then
 		echo "Starting UCC local mode"
 		ucc_image_local
