* Update the UCC rollout handling (Bug #28327)
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.1/ucc@37559 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/univention-ucc-initramfs/initramfs-tools/scripts/ucc b/univention-ucc-initramfs/initramfs-tools/scripts/ucc
--- a/univention-ucc-initramfs/initramfs-tools/scripts/ucc
+++ b/univention-ucc-initramfs/initramfs-tools/scripts/ucc
@@ -801,8 +801,22 @@ ucc_image_ro()
 # Rollout
 ucc_rollout ()
 {
+	# Load keyboard drivers
+	modprobe i8042
+	modprobe atkbd
+
+	# Ensure the console is prepared for the user interaction
+	run_scripts /scripts/panic
+
 	if [ ! -e /root/var/univention-join/joined ]; then
-		chroot /root /usr/sbin/univention-join
+		mount -o move /proc /root/proc
+		if ! chroot /root /usr/sbin/univention-join; then
+			mount -o move /root/proc /proc
+			echo "ERROR: Failed to join."
+			panic "Dropping to a shell!"
+		else
+			mount -o move /root/proc /proc
+		fi
 	fi
 }
 
